Vagrant.configure("2") do |config|
   config.vm.define "web" do |web|
      web.vm.box = "generic/rhel8"
      web.vm.hostname = "lnxrhel8"
      web.vm.network "private_network", ip: "192.168.56.15"
      web.vm.provider "virtualbox" do |vb|
          vb.memory = "512"
          vb.cpus = "1"
          vb.linked_clone = true
          vb.name = "lnxrhel8"
      end
      web.trigger.before :destroy do |trigger|
        trigger.warn = "Remove subscription for redhat"
        trigger.run_remote = {inline: "subscription-manager remove --all"}
      end
   end
 config.vm.provision "ansible" do |ansible|
  ansible.playbook = "../../../ansible/ansible_deploy_vagrant/create-user-vagrant.yml"
  ansible.host_vars = {
    "web" => {"remove_ip"=>"192.168.56.15",
              "install_pkg"=>"true" 
              }
  }
 end
end
