---
- hosts: all
  gather_facts: true
  become: true
  vars:
   package_okd:
    - wget
    - git
    - net-tools
    - bind-utils
    - yum-utils
    - iptables-services
    - bridge-utils
    - bash-completion
    - kexec-tools
    - sos
    - psacct
    - vim-enhanced
    - vim
    - telnet
    - docker-1.13.1
    - java-1.8.0-openjdk-headless
    - httpd-tools
    - ntp
    - python-passlib
    - python-ipaddress
    - PyYAML bind
    - ceph-common
    - dnsmasq
    - docker
    - firewalld
    - flannel
    - glusterfs-fuse
    - iptables
    - iptables-services
    - iscsi-initiator-utils
    - libselinux-python
    - nfs-utils
    - ntp
    - openssl
    - origin
    - origin-node
    - pyparted
    - python-httplib2
  tasks:

    - name: add subscriptions for okd
      shell: |
        yum-config-manager –-enable rhel-7-server-extras-rpms
        yum-config-manager –-enable rh-gluster-3-client-for-rhel-7-server-rpms
        yum-config-manager –-enable rhel-7-server-optional-rpms
        yum-config-manager –-enable rhel-7-server-ansible-2.9-rpms

    - name: install packages
      yum:
        name: "{{item}}"
        state: present
      with_items: '{{package_okd}}'
      ignore_errors: true

