---
      - name: Create groups administrator
        group:
          name: "{{item}}"
          state: present
        with_items:
          - '{{usuarios}}'

      - name: Create user administrator
        user:
          name: '{{item}}'
          group: cnvadmin
          state: present
          shell: /bin/bash
          append: yes
        with_items:
          - '{{usuarios}}'

      - name: "Brindar acceso al total de usuarios"
        lineinfile:
          path: /etc/sudoers
          regexp: '^%cnvadmin.*ALL.*NOPASSWD.*ALL'
          line: '%cnvadmin ALL=(ALL) NOPASSWD:ALL'
          validate: /usr/sbin/visudo -cf %s
          backup: yes

      - name: Ensures dir exists
        file:
          path: '/home/{{item}}/.ssh'
          state: directory
          owner: '{{item}}'
          group: cnvadmin
        with_items:
          - '{{usuarios}}'
        when: ansible_distribution != "Solaris"

      - name: Ensures dir exists
        file:
          path: '/export/home/{{item}}/.ssh'
          state: directory
          owner: '{{item}}'
          group: cnvadmin
        with_items:
          - '{{usuarios}}'
        when: ansible_distribution == "Solaris"

      - name: copy publicy key to os vagrant Linux
        copy:
          src: /home/eflores/.ssh/id_rsa.pub
          dest: /home/{{item}}/.ssh/authorized_keys
          mode: '0644'
          owner: '{{item}}'
          group: cnvadmin
        with_items:
          - '{{usuarios}}'
        when: ansible_distribution != "Solaris"

      - name: copy
        copy:
          src: ../../../../../templates/authorized_keys/{{item}}/id_rsa.pub
          dest: /export/home/{{item}}/.ssh/authorized_keys
          mode: '0644'
          owner: '{{item}}'
          group: cnvadmin
        with_items:
          - '{{usuarios}}'
        when: ansible_distribution == "Solaris"

      - name: Insert/Update "Match User" configuration block in /etc/ssh/sshd_config
        lineinfile:
          path: /etc/ssh/sshd_config
          regexp: '^PasswordAuthentication'
          line: 'PasswordAuthentication yes'
          backup: yes
        notify:
          - restart sshd

      - name: remove ip asigned to eflores user
        lineinfile:
          path: "/home/eflores/.ssh/known_hosts"
          regexp: "^{{remove_ip}}.*"
          state: absent
        delegate_to: localhost
        ignore_errors: true
