port = ENV["USERACCOUNT"]
Vagrant.configure("2") do |config|
 config.vm.provision "shell" do |s|
  s.inline = "echo $1 > /tmp/passwd.txt"
  s.args = port 
 end
 config.vm.provision "shell", path: "~/data/scripts/bash/check_so_vagrant.sh"
 config.vm.define "web" do |web|
      web.vm.box = "generic/rhel7"
      web.vm.box_version = "3.6.12"
      web.vm.hostname = "lnxrh7"
      web.vm.network "private_network", ip: "192.168.56.14"
      web.vm.provider "virtualbox" do |vb|
          vb.memory = "512"
          vb.cpus = "1"
          vb.linked_clone = true
          vb.name = "lnxrh7"
      end
      #web.trigger.before :destroy do |trigger|
      #  trigger.run_remote={inline: "subscription-manager unregister"}
      #end
  end
 config.vm.provision "ansible" do |ansible|
  ansible.limit = "all"
  ansible.extra_vars = {
    remove_ip: "192.168.56.14",
    install_pkg: "true"
  }
  ansible.playbook = "/Users/edwinflores/data/ansible/personal/deploy-users-sw-vagrant/create-user-vagrant.yml"
 end
end
