Vagrant.configure("2") do |config|

  config.vm.provision "shell",
    type: "shell",
    preserve_order: true,
    inline: <<-SHELL
          #!/bin/sh
      _registration_os_suse(){
          SUSEConnect -e loquitoslack@gmail.com -r 419F58B555869027
      }
       _deregistration_os_suset(){
          SUSEConnect -d
      }
      _registration_os_redhat(){
            if [ `which subscription-manager` ]
            then
                 subscription-manager register --username=eefloresb.pe --password="K4rr45k0?*1981" --auto-attach --force
            fi
       }
       _deregistration_os_redhat(){
            if [ `which subscription-manager` ]
            then
              subscription-manager unregister
            fi
       }
      _get_Amazon(){
          os=$1
          version=${2}
      }
      _get_Suse(){
          os=$1
          version=${2}
      }
      _get_RedHat(){
           os=$1
           version=$2
           band=false
           if [ `which subscription-manager 2>/dev/null` ]; then
                if [ `subscription-manager status | grep Overall | cut -d : -f 2 | tr -d " "` == "Unknown" ]
                then
                    _registration_os_redhat
                    band=false
                fi
           fi
           ### Desactiva repositorio epel para oracle
           if [ $os = "Oracle" ]; then
                sed -i -e "/enabled/s/1/0/" /etc/yum.repos.d/epel.repo
           fi
           if [[ $version -gt 7 ]]; then
               dnf install python2
               ln -s /usr/bin/python2 /usr/bin/python
           elif [[ $version -eq 7 ]]; then
                echo -e "LANG=en_US.UTF-8\nLC_ALL=en_US.UTF-8" > /etc/environment
           elif [[ $version -eq 6 ]]; then
                yum install -y libselinux-python --nogpgcheck
           elif [[ $version -eq 5 ]]; then
                yum install -y epel-release --nogpgcheck
                yum install -y python26 --nogpgcheck
           fi

           if [ $band == true ]; then
                _deregistration_os_redhat
           fi
      }

      _get_Debian(){
           os=$1
           version=$2
           apt-get update
           if [ $os == "ubuntu" ] && [ ${version%%.*} -le 16 ]
           then
            export DEBIAN_FRONTEND=noninteractive
            apt-get install -y python
           fi
      }

      _check_distro(){
           if [ -f /etc/redhat-release ]
           then
              if [[ $(grep -ow "Red Hat" /etc/redhat-release) == "Red Hat" ]]
              then
                    if [ -f /etc/oracle-release ]
                    then
                        os="Oracle"
                    else
                        os="RedHat"
                    fi
               elif [[ `grep -w "ID" /etc/os-release | awk -F = '{print $2}' | tr -d '"'` == "centos" ]]
               then
                         os="CentOS"
              fi
              version=`grep -woE '[[:digit:]].*' /etc/redhat-release | cut -d "." -f1`
              _get_RedHat $os $version
           elif [ -f /etc/release ]
           then
                os=`grep -woi solaris /etc/release`
                version=`grep -Ewoi [[:digit:]].[[:digit:]]+ /etc/release`
           elif [ -f /etc/os-release ]
           then
                os=`grep -w "ID" /etc/os-release | awk -F = '{print $2}' | tr -d '"'`
                version=`grep -w "VERSION_ID" /etc/os-release | awk -F = '{print $2}' | tr -d '"'`
                if [ $os == "ubuntu" ] || [ $os == "debian"]
                then
                     _get_Debian $os $version
                elif [ $os == 'sles' ]
                then
                    _get_Suse $os $version
                elif [ $os == 'amzn' ]
                then
                    _get_Amazon $os $version
                fi
           fi
        }

   _check_distro

    SHELL

      config.vm.define "antlet70" do |antlet70|
          antlet70.vm.box = "centos/7"
          antlet70.vm.hostname = "antlet70.slackwarnet.com"
          antlet70.vm.network "private_network", ip: "192.168.33.231"
          antlet70.vm.provider "virtualbox" do |vb|
          vb.memory = "1024"
          vb.cpus = "1"
          vb.linked_clone = true
          vb.name = "antlet70"
        end
      end

      config.vm.define "antlet71" do |antlet71|
          antlet71.vm.box = "generic/rhel7"
          antlet71.vm.hostname = "antlet71.slackwarnet.com"
          antlet71.vm.network "private_network", ip: "192.168.33.232"
          antlet71.vm.provider "virtualbox" do |vb|
            vb.memory = "256"
            vb.cpus = "1"
            vb.linked_clone = true
            vb.name = "antlet71"
        end
      end

      config.vm.define "antlet72" do |antlet72|
          antlet72.vm.box = "generic/rhel7"
          antlet72.vm.hostname = "antlet72.slackwarnet.com"
          antlet72.vm.network "private_network", ip: "192.168.33.233"
          antlet72.vm.provider "virtualbox" do |vb|
            vb.memory = "256"
            vb.cpus = "1"
            vb.linked_clone = true
            vb.name = "antlet72"
        end
      end

      config.vm.define "antlet73" do |antlet73|
          antlet73.vm.box = "generic/rhel7"
          antlet73.vm.hostname = "antlet73.slackwarnet.com"
          antlet73.vm.network "private_network", ip: "192.168.33.234"
          antlet73.vm.provider "virtualbox" do |vb|
            vb.memory = "256"
            vb.cpus = "1"
            vb.linked_clone = true
            vb.name = "antlet73"
        end
      end

      config.vm.define "antlet74" do |antlet74|
          antlet74.vm.box = "generic/rhel7"
          antlet74.vm.hostname = "antlet74.slackwarnet.com"
          antlet74.vm.network "private_network", ip: "192.168.33.235"
          antlet74.vm.provider "virtualbox" do |vb|
            vb.memory = "256"
            vb.cpus = "1"
            vb.linked_clone = true
            vb.name = "antlet74"
        end
      end

      config.vm.provision "ansible" do |ansible|
       ansible.playbook = "/Users/edwinflores/Documents/github.com/MyProjects/ansible/playbooks/create-user-vagrant.yml"
       ansible.host_vars = {
         "antlet70" => {"remove_ip" => "192.168.33.231"},
         "antlet71" => {"remove_ip" => "192.168.33.232"},
         "antlet72" => {"remove_ip" => "192.168.33.233"},
         "antlet73" => {"remove_ip" => "192.168.33.234"},
         "antlet74" => {"remove_ip" => "192.168.33.235"}
       }
    end
end
